version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: snakers_db
    environment:
      POSTGRES_USER: sneak
      POSTGRES_PASSWORD: sneak234
      POSTGRES_DB: sneakBD
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sneak -d sneakBD"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: snakers_bot
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      DATABASE_URL: "postgres://sneak:sneak234@postgres:5432/sneakBD?sslmode=disable"
    restart: unless-stopped

volumes:
  postgres_data: